### PR TITLE
Touché 2022

### PR DESCRIPTION
**Pull request by heinrichreimer**
Unfortunately I did not make it until after the qrels were released but here it is: Touché 2022

This adds new docs:
- `argsme2020-04-01/processed` (preprocessed for task 1)
- `clueweb12/touche-2022-task-2` (passages extracted from ClueWeb12)
- `clueweb12/touche-2022-task-2/expanded-doc-t5-query`
- `touche-image/2022-06-13` (argument image dataset, will be re-used in 2023)

And of course queries and qrels:
- `argsme2020-04-01/processed/touche-2022-task-1`
- `clueweb12/touche-2022-task-2`
- `touche-image/2022-06-13/touche-2022-task-3`

Still some testing and adjustments to be done but it should be ready tomorrow.

### CODE REVIEW

**Comment by heinrichreimer** [comment]
Yep, all tests seem fine :+1: 
Lets get this merged!

**Comment by seanmacavaney** [comment]
Awesome, thanks! Running on my end now, generating metadata, documentation pages, etc. I'll keep you posted if I need anything else.

**Comment by seanmacavaney** [comment]
All set on my side, thanks @heinrichreimer!

**Comment by seanmacavaney** [comment]
No problem; pushed as `ir-datasets==0.5.4`! https://pypi.org/project/ir-datasets/

**Comment by heinrichreimer** [comment]
Thanks :fireworks:

**Pull request merged**
